const CLEANUP_INTERVAL = 1 * 60000; // 1 minute
const SUBMISSION_EXPIRY = 1 * 60 * 60 * 1000; // 1 hour
const VERIFICATION_THRESHOLD = 80;

module.exports = {
  CLEANUP_INTERVAL,
  SUBMISSION_EXPIRY,
  VERIFICATION_THRESHOLD
};